services:
  tienda:
    build: .
    container_name: tienda-aloha
    restart: unless-stopped
    ports:
      - "5070:5000"
    volumes:
      - tienda-data:/app/instance
      - ./static/images:/app/static/images
    env_file:
      - .env
    command: ["python", "run.py"]

volumes:
  tienda-data:
